// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0wn3ZBULY7rdOAw2Ga88b0FVTbjatK0k',
    appId: '1:872335024678:web:121d7212edd0145a7dbce7',
    messagingSenderId: '872335024678',
    projectId: 'warewatch2026',
    authDomain: 'warewatch2026.firebaseapp.com',
    storageBucket: 'warewatch2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ovfDqKXELFxej1Yi1zeriML59xwICq4',
    appId: '1:872335024678:android:45d24546348e06bb7dbce7',
    messagingSenderId: '872335024678',
    projectId: 'warewatch2026',
    storageBucket: 'warewatch2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAfUTJ5WUZ_LbanEjqQ_cbj9GfAr7Wyc',
    appId: '1:872335024678:ios:8a7e160b7e5437247dbce7',
    messagingSenderId: '872335024678',
    projectId: 'warewatch2026',
    storageBucket: 'warewatch2026.firebasestorage.app',
    iosBundleId: 'com.example.warewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAAfUTJ5WUZ_LbanEjqQ_cbj9GfAr7Wyc',
    appId: '1:872335024678:ios:8a7e160b7e5437247dbce7',
    messagingSenderId: '872335024678',
    projectId: 'warewatch2026',
    storageBucket: 'warewatch2026.firebasestorage.app',
    iosBundleId: 'com.example.warewatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0wn3ZBULY7rdOAw2Ga88b0FVTbjatK0k',
    appId: '1:872335024678:web:584aba28c7dbbe617dbce7',
    messagingSenderId: '872335024678',
    projectId: 'warewatch2026',
    authDomain: 'warewatch2026.firebaseapp.com',
    storageBucket: 'warewatch2026.firebasestorage.app',
  );
}
